import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ELM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center align-center text-center py-10  h-[50vh] my-6 ">
        <div className="area">
          <ul className="circles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>
        </div>
        <div className="text-7xl  animate-fade-in ">Hello !</div>
        <div className="text-xl mt-10 font-serif tracking-wide animate-fade-in-slow ">
          Welcome To Employo, A safe place for Employees
        </div>
      </div>
    </div>
  );
}
