import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ELM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  justify-center align-center text-center py-10 px-8  h-[50vh] my-6 w-[60%] mx-auto rounded-[15px] glass ">
        <div className="w-[50%] my-auto">
          <img
            className="animate-fade-in h-[25vh] w-auto m-auto rounded-full"
            src="https://png.pngtree.com/png-vector/20220901/ourmid/pngtree-company-employee-avatar-icon-wearing-a-suit-png-image_6133899.png"
            alt=""
          />
        </div>
        <div className="w-[50%] my-auto">
          <h1 className="text-left text-2xl font-bold animate-fade-in">
            What is it?
          </h1>
          <div className="text-lg text-left mt-10  tracking-wide animate-fade-in ">
            Employo is an Employee Satisfaction based Application which focusses
            on conveying important demands of employees to the higher
            authorities
          </div>
        </div>
      </div>
    </div>
  );
}
